[provider]
cluster = "localnet"
wallet = "~/.config/safecoin/id.json"

[programs.localnet]
basic_2 = "ancAHhi4TqE5nwR29gPGhGV8CYLgHUFEDfE1q12nRK3"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
